// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnihfozemqwlgruswtpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuaWhmb3plbXF3bGdydXN3dHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTQ2MzQsImV4cCI6MjA3NDM3MDYzNH0.23Ma-cBaMOF0y2cF2lsI0wD2An53vEeEJTPs5vAc_Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});